(()=>{
"use strict";
const D=window.GAME_DATA;
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const view=$("#view"),modal=$("#modal"),modalBody=$("#modalBody"),toast=$("#toast");
const STORAGE="teacherQuest2569_v3";
const today=()=>new Date().toLocaleDateString("sv-SE");
const shuffle=a=>a.slice().sort(()=>Math.random()-.5);
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const letters=["ก","ข","ค","ง"];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const defaults={xp:0,coins:0,maxCombo:0,records:{},bookmarks:[],examHistory:[],daily:{date:today(),count:0},settings:{music:true,sound:true,volume:.35,reduced:false},lastModule:"all"};
let state=load();
let currentView="home",battle=null,exam=null,timer=null,toastTimer=null,audio=null,musicTimer=null;
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE)||"{}");return deep(defaults,s)}catch{return structuredClone(defaults)}}
function deep(a,b){const out=Array.isArray(a)?a.slice():{...a};Object.keys(b||{}).forEach(k=>{out[k]=a&&typeof a[k]==="object"&&!Array.isArray(a[k])&&typeof b[k]==="object"?deep(a[k],b[k]):b[k]});return out}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));updateHud()}
function dailyReset(){if(state.daily.date!==today())state.daily={date:today(),count:0}}
function record(q,ok){const r=state.records[q.id]||{attempts:0,correct:0,lastWrong:false};r.attempts++;if(ok)r.correct++;r.lastWrong=!ok;r.lastAt=Date.now();state.records[q.id]=r;state.daily.count++;if(ok){state.xp+=8;state.coins+=3}else{state.xp+=2;state.coins+=1}save()}
function level(){return Math.floor(state.xp/100)+1}
function rank(){const l=level();return l>=20?"ปรมาจารย์แห่งสนามสอบ":l>=12?"อัศวินวิชาชีพ":l>=6?"นักรบความรู้":"ผู้ฝึกหัด"}
function stats(){const rs=Object.values(state.records),attempts=rs.reduce((s,r)=>s+r.attempts,0),correct=rs.reduce((s,r)=>s+r.correct,0);return{attempted:rs.length,attempts,correct,accuracy:attempts?Math.round(correct/attempts*100):0,weak:D.questions.filter(q=>{const r=state.records[q.id];return !r||r.correct/r.attempts<.7}).length}}
function updateHud(){dailyReset();const s=stats(),lv=level(),inLevel=state.xp%100;$("#topLevel").textContent=lv;$("#topCoins").textContent=state.coins;$("#rankName").textContent=rank();$("#xpText").textContent=`${inLevel} / 100`;$("#xpBar").style.width=inLevel+"%";$("#sideStreak").textContent=state.maxCombo;$("#sideMastery").textContent=s.accuracy;$("#dailyQuestBar").style.width=clamp(state.daily.count/10*100,0,100)+"%";$("#dailyQuestCount").textContent=`${Math.min(state.daily.count,10)} / 10`;$("#musicBtn").classList.toggle("off",!state.settings.music);$("#soundBtn").classList.toggle("off",!state.settings.sound);document.body.classList.toggle("no-motion",state.settings.reduced)}
function validate(){const errors=[];if(!D||!Array.isArray(D.questions))errors.push("ไม่พบคลังข้อสอบ");else{const ids=new Set();D.questions.forEach((q,i)=>{if(ids.has(q.id))errors.push(`รหัสซ้ำ ${q.id}`);ids.add(q.id);if(!Array.isArray(q.options)||q.options.length!==4)errors.push(`ข้อ ${i+1} ตัวเลือกไม่ครบ`);if(!Number.isInteger(q.answer)||q.answer<0||q.answer>3)errors.push(`ข้อ ${i+1} เฉลยผิดรูปแบบ`);if(!D.modules.some(m=>m.id===q.module))errors.push(`ข้อ ${i+1} ไม่พบหมวด`)})}return errors}
function showToast(msg){toast.textContent=msg;toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove("show"),2200)}
function openModal(html){modalBody.innerHTML=html;modal.classList.remove("hidden");setTimeout(()=>$("button,input,select",modalBody)?.focus(),30)}
function closeModal(){modal.classList.add("hidden");modalBody.innerHTML=""}
function ensureAudio(){if(audio)return audio;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;audio=new AC();return audio}
function tone(freq=440,d=.08,type="square",gain=.08,delay=0){if(!state.settings.sound)return;const ac=ensureAudio();if(!ac)return;if(ac.state==="suspended")ac.resume();const o=ac.createOscillator(),g=ac.createGain(),t=ac.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(gain*state.settings.volume,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g).connect(ac.destination);o.start(t);o.stop(t+d)}
const sfx={select:()=>tone(520,.05),correct:()=>{tone(660,.09);tone(880,.12,"square",.07,.08)},wrong:()=>{tone(190,.16,"sawtooth");tone(120,.18,"sawtooth",.06,.08)},hit:()=>tone(110,.08,"sawtooth",.12),win:()=>[523,659,784,1047].forEach((n,i)=>tone(n,.18,"square",.07,i*.11)),level:()=>[440,554,659,880].forEach((n,i)=>tone(n,.15,"square",.07,i*.08))};
function startMusic(){if(!state.settings.music||musicTimer)return;const ac=ensureAudio();if(!ac)return;if(ac.state==="suspended")ac.resume();let step=0;const seq=[220,277,330,440,330,277,247,330];musicTimer=setInterval(()=>{if(!state.settings.music)return;const n=seq[step++%seq.length];const was=state.settings.sound;state.settings.sound=true;tone(n,.18,"triangle",.022);state.settings.sound=was},260)}
function stopMusic(){clearInterval(musicTimer);musicTimer=null}
function musicToggle(){state.settings.music=!state.settings.music;state.settings.music?startMusic():stopMusic();save();showToast(state.settings.music?"เปิดเพลงแล้ว":"ปิดเพลงแล้ว")}
function soundToggle(){state.settings.sound=!state.settings.sound;save();if(state.settings.sound)sfx.select();showToast(state.settings.sound?"เปิดเสียงเอฟเฟกต์แล้ว":"ปิดเสียงเอฟเฟกต์แล้ว")}
function playerArt(){return '<div class="pixel-fighter"><i class="head"></i><i class="body"></i><i class="weapon"></i></div>'}
function heroArt(){return '<div class="hero-art"><div class="portal"></div><div class="teacher-sprite"><i class="hair"></i><i class="face"></i><i class="body"></i><i class="book"></i><i class="legs"></i></div><div class="float-badge one">16 ดินแดน</div><div class="float-badge two">'+D.questions.length+' ภารกิจ</div></div>'}
function module(id){return D.modules.find(m=>m.id===id)}
function moduleStats(id){const qs=D.questions.filter(q=>q.module===id);let attempts=0,correct=0,done=0;qs.forEach(q=>{const r=state.records[q.id];if(r){done++;attempts+=r.attempts;correct+=r.correct}});return{total:qs.length,done,accuracy:attempts?Math.round(correct/attempts*100):0}}
function go(name,opts={}){currentView=name;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));view.className="view";clearInterval(timer);timer=null;if(name!=="practice")battle=null;if(name!=="exam")exam=null;const render={home:renderHome,world:renderWorld,practice:()=>renderPractice(opts),exam:renderExamLobby,review:renderReview,codex:renderCodex,profile:renderProfile}[name]||renderHome;render();window.scrollTo({top:0,behavior:"smooth"})}
function renderHome(){const s=stats(),strongest=[...D.modules].sort((a,b)=>moduleStats(b.id).accuracy-moduleStats(a.id).accuracy)[0];view.innerHTML=`<section class="hero pixel-box"><div class="hero-grid"><div><div class="eyebrow">MISSION 2569 • READY FOR THE EXAM</div><h1>ฝึกให้แม่น<br><span>สู้ให้ติด</span></h1><p>ออกเดินทางผ่านศาสตร์การสอน กฎหมาย วิชาชีพ และสถานการณ์การศึกษา ฝึกตอบแบบต่อสู้ เก็บคอมโบ แล้วพิชิตสนามสอบใหญ่</p><div class="hero-actions"><button class="btn" id="quickStart">⚔ เริ่มภารกิจทันที</button><button class="btn mint" data-go="world">🗺️ เลือกดินแดน</button><button class="btn dark" data-go="exam">⏱️ สนามสอบใหญ่</button></div></div>${heroArt()}</div></section>
<div class="section-head"><div><h2>สถานะการเดินทาง</h2><p>ดูจุดแข็งและภารกิจที่รออยู่</p></div></div><section class="dashboard"><div class="stat-card pixel-box"><b>${s.attempted}</b><span>ข้อที่เผชิญแล้ว</span></div><div class="stat-card pixel-box"><b>${s.accuracy}%</b><span>ความแม่นยำรวม</span></div><div class="stat-card pixel-box"><b>${state.maxCombo}</b><span>คอมโบสูงสุด</span></div><div class="stat-card pixel-box"><b>${s.weak}</b><span>ข้อที่ยังต้องฝึก</span></div></section>
<div class="section-head"><div><h2>ทางลัดนักผจญภัย</h2><p>เลือกสนามให้ตรงกับเป้าหมายวันนี้</p></div></div><section class="quest-strip"><button class="quest-card pixel-box" id="weakStart"><span class="quest-ico">🧠</span><span><h3>ล่าจุดอ่อน</h3><p>ระบบเลือกข้อที่ยังไม่แม่น</p></span><b>+EXP</b></button><button class="quest-card pixel-box" id="lawStart"><span class="quest-ico">⚖️</span><span><h3>ศึกกฎหมาย</h3><p>รวมกฎหมายและวิชาชีพฉบับตรวจทาน</p></span><b>BOSS</b></button><button class="quest-card pixel-box" data-go="codex"><span class="quest-ico">📚</span><span><h3>เปิดคัมภีร์</h3><p>สูตรจำและแหล่งอ้างอิงทางการ</p></span><b>READ</b></button></section>
<div class="section-head"><div><h2>ดินแดนแนะนำ</h2><p>${strongest?`ดินแดนที่คุณทำได้ดีที่สุด: ${esc(strongest.title)}`:"เริ่มด่านแรกเพื่อเปิดสถิติ"}</p></div><button class="btn small dark" data-go="world">ดูทั้งหมด</button></div><section class="world-map">${D.modules.slice(0,4).map(zoneHtml).join("")}</section><div class="footer-note">ครูเควสต์ • คลังความรู้ฉบับ ${D.version} • ตรวจข้อมูลผันแปรล่าสุด ${D.verifiedAt}</div>`;bindCommon();$("#quickStart").onclick=()=>startBattle({mode:"random",count:10});$("#weakStart").onclick=()=>startBattle({mode:"weak",count:10});$("#lawStart").onclick=()=>startBattle({mode:"modules",modules:["eduact","child","disability","civil","ksp","voclaw"],count:12})}
function zoneHtml(m){const s=moduleStats(m.id),pct=Math.round(s.done/s.total*100),stars=s.accuracy>=85?"★★★":s.accuracy>=70?"★★☆":s.done?"★☆☆":"☆☆☆";return `<button class="zone ${s.accuracy>=80?'mastered':''}" data-module="${m.id}"><span class="stars">${stars}</span><span class="zone-no">ZONE ${String(D.modules.indexOf(m)+1).padStart(2,"0")}</span><div class="zone-icon">${m.icon}</div><h3>${esc(m.title)}</h3><p>${esc(m.summary)}</p><div class="zone-meta"><span>${s.done}/${s.total} ข้อ</span><span>${s.accuracy}%</span></div><div class="meter"><i style="width:${pct}%"></i></div></button>`}
function renderWorld(){view.innerHTML=`<section class="panel pixel-box"><div class="panel-title"><div><h2>แผนที่ภารกิจ</h2><small>เลือกดินแดนเพื่อท้าทายบอสประจำศาสตร์</small></div><button class="btn small" id="allRandom">สุ่มทุกดินแดน</button></div><div class="world-map">${D.modules.map(zoneHtml).join("")}</div></section>`;$$('.zone').forEach(z=>z.onclick=()=>openZone(z.dataset.module));$("#allRandom").onclick=()=>startBattle({mode:"random",count:15})}
function openZone(id){const m=module(id),s=moduleStats(id);openModal(`<h2 id="modalTitle">${m.icon} ${esc(m.title)}</h2><p>${esc(m.summary)}</p><div class="dashboard"><div class="stat-card pixel-box"><b>${s.total}</b><span>ข้อในด่าน</span></div><div class="stat-card pixel-box"><b>${s.accuracy}%</b><span>ความแม่นยำ</span></div></div><h3>บอสประจำด่าน</h3><p>👾 ${esc(m.boss)}</p><div class="hero-actions"><button class="btn" id="zoneNormal">เริ่มด่าน 10 ข้อ</button><button class="btn pink" id="zoneBoss">ท้าบอส 15 ข้อ</button></div>`);$("#zoneNormal").onclick=()=>{closeModal();startBattle({mode:"module",module:id,count:10})};$("#zoneBoss").onclick=()=>{closeModal();startBattle({mode:"module",module:id,count:15,boss:true})}}
function renderPractice(opts={}){if(opts.start){startBattle(opts.start);return}view.innerHTML=`<section class="panel pixel-box"><div class="panel-title"><div><h2>สนามฝึก</h2><small>เลือกวิธีฝึก แล้วเปลี่ยนความรู้เป็นพลังโจมตี</small></div></div><div class="filter-row"><select id="practiceModule"><option value="all">ทุกดินแดน</option>${D.modules.map(m=>`<option value="${m.id}" ${state.lastModule===m.id?'selected':''}>${m.icon} ${esc(m.title)}</option>`).join("")}</select></div><div class="mode-grid"><button class="mode-card" data-mode="normal"><div class="mode-icon">⚔️</div><h3>ศึกมาตรฐาน</h3><p>สุ่ม 10 ข้อ ตอบถูกโจมตี ตอบผิดถูกสวนกลับ</p><span class="tag">10 QUESTIONS</span></button><button class="mode-card" data-mode="boss"><div class="mode-icon">👾</div><h3>ล่าบอส</h3><p>15 ข้อ ระดับกลางและยาก บอสพลังชีวิตสูง</p><span class="tag">HARD MODE</span></button><button class="mode-card" data-mode="weak"><div class="mode-icon">🧠</div><h3>ห้องล้างแค้น</h3><p>ระบบเลือกข้อที่เคยผิดหรือยังไม่เคยทำ</p><span class="tag">SMART REVIEW</span></button></div></section>`;$$('.mode-card').forEach(b=>b.onclick=()=>{const mid=$("#practiceModule").value;state.lastModule=mid;save();if(b.dataset.mode==="weak")startBattle({mode:"weak",module:mid==="all"?null:mid,count:10});else startBattle({mode:mid==="all"?"random":"module",module:mid==="all"?null:mid,count:b.dataset.mode==="boss"?15:10,boss:b.dataset.mode==="boss"})})}
function pickPool(cfg){let pool=D.questions;if(cfg.mode==="module")pool=pool.filter(q=>q.module===cfg.module);if(cfg.mode==="modules")pool=pool.filter(q=>cfg.modules.includes(q.module));if(cfg.module)pool=pool.filter(q=>q.module===cfg.module);if(cfg.mode==="weak")pool=pool.filter(q=>{const r=state.records[q.id];return !r||r.lastWrong||r.correct/r.attempts<.7});if(cfg.boss)pool=pool.filter(q=>q.difficulty!=="ง่าย");if(pool.length<(cfg.count||10)){const extra=D.questions.filter(q=>!pool.includes(q));pool=pool.concat(shuffle(extra))}return shuffle(pool).slice(0,cfg.count||10)}
function startBattle(cfg){battle={pool:pickPool(cfg),index:0,playerHp:100,enemyHp:cfg.boss?150:100,enemyMax:cfg.boss?150:100,combo:0,selected:null,locked:false,hidden:[],shield:false,skills:{fifty:1,heal:1,shield:1,hint:1},boss:!!cfg.boss,correct:0};currentView="practice";$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view==="practice"));renderBattle();window.scrollTo({top:0,behavior:"smooth"})}
function renderBattle(){if(!battle||battle.index>=battle.pool.length){finishBattle();return}const q=battle.pool[battle.index],m=module(q.module);view.innerHTML=`<section class="battle-shell pixel-box"><div class="battle-hud"><div><div class="fighter-name">🧙 ครูนักผจญภัย</div><div class="hpbar"><i id="playerHp" style="width:${battle.playerHp}%"></i></div></div><div class="battle-center"><strong>${battle.index+1} / ${battle.pool.length}</strong><small>COMBO ×${battle.combo}</small></div><div><div class="fighter-name right">${esc(battle.boss?m.boss:"มอนสเตอร์ความสับสน")} 👾</div><div class="hpbar enemy-hp"><i id="enemyHp" style="width:${battle.enemyHp/battle.enemyMax*100}%"></i></div></div></div><div class="arena"><div class="fighter player" id="playerFighter">${playerArt()}</div><div class="fighter enemy" id="enemyFighter">${playerArt()}</div></div><div class="question-panel"><div class="question-meta"><span class="chip gold">${m.icon} ${esc(m.title)}</span><span class="chip">${esc(q.difficulty)}</span><span class="chip">${esc(q.type)}</span>${q.verified?`<span class="chip mint">ตรวจ ${esc(q.verifiedAt)}</span>`:""}</div><div class="question-text">${esc(q.question)}</div><div class="options">${q.options.map((o,i)=>`<button class="option ${battle.selected===i?'selected':''}" data-answer="${i}" ${battle.locked||battle.hidden.includes(i)?'disabled':''} style="${battle.hidden.includes(i)?'visibility:hidden':''}"><span class="letter">${letters[i]}</span>${esc(o)}</button>`).join("")}</div><div class="battle-actions"><div class="skills"><button class="skill" data-skill="fifty" ${!battle.skills.fifty||battle.locked?'disabled':''}>✂ 50:50</button><button class="skill" data-skill="shield" ${!battle.skills.shield||battle.locked?'disabled':''}>🛡 โล่</button><button class="skill" data-skill="heal" ${!battle.skills.heal||battle.locked?'disabled':''}>💚 ฟื้นพลัง</button><button class="skill" data-skill="hint" ${!battle.skills.hint||battle.locked?'disabled':''}>💡 คำใบ้</button></div><button class="btn" id="attackBtn" ${battle.selected===null||battle.locked?'disabled':''}>โจมตี!</button></div><div id="feedbackSlot"></div></div></section>`;$$('.option').forEach(b=>b.onclick=()=>{if(battle.locked)return;battle.selected=Number(b.dataset.answer);sfx.select();renderBattle()});$$('.skill').forEach(b=>b.onclick=()=>useSkill(b.dataset.skill));$("#attackBtn").onclick=submitBattle}
function useSkill(skill){const q=battle.pool[battle.index];if(!battle.skills[skill])return;battle.skills[skill]--;if(skill==="fifty"){battle.hidden=shuffle([0,1,2,3].filter(i=>i!==q.answer)).slice(0,2);showToast("ตัดตัวลวงออก 2 ตัวเลือก")};if(skill==="shield"){battle.shield=true;showToast("กางโล่แล้ว: ป้องกันการโจมตีครั้งถัดไป")};if(skill==="heal"){battle.playerHp=clamp(battle.playerHp+25,0,100);showToast("ฟื้นพลัง 25 HP")};if(skill==="hint")openModal(`<h2 id="modalTitle">💡 คำใบ้</h2><p>จับคำสำคัญในโจทย์: <strong>${esc(q.type)}</strong></p><p>${esc(q.explanation.split(" ").slice(0,12).join(" "))}…</p>`);renderBattle()}
function submitBattle(){if(battle.locked||battle.selected===null)return;const q=battle.pool[battle.index],ok=battle.selected===q.answer;battle.locked=true;record(q,ok);let damage=0;if(ok){battle.combo++;battle.correct++;state.maxCombo=Math.max(state.maxCombo,battle.combo);damage=22+Math.min(battle.combo*3,18);battle.enemyHp=clamp(battle.enemyHp-damage,0,battle.enemyMax);sfx.correct();animateAttack(damage)}else{battle.combo=0;damage=battle.shield?0:18;battle.shield=false;battle.playerHp=clamp(battle.playerHp-damage,0,100);sfx.wrong();animateHurt(damage)}save();const options=$$('.option');options.forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');if(i===battle.selected&&!ok)b.classList.add('wrong')});const slot=$("#feedbackSlot");slot.innerHTML=`<div class="feedback ${ok?'':'bad'}"><h3>${ok?'โจมตีสำเร็จ!':'ถูกสวนกลับ!'}</h3><p><strong>คำตอบ: ${letters[q.answer]}. ${esc(q.options[q.answer])}</strong></p><p>${esc(q.explanation)}</p><div class="source">แหล่งทบทวน: ${esc(q.source)}${q.verified?` • ตรวจ ${esc(q.verifiedAt)}`:""}</div><div class="hero-actions"><button class="btn small ${battle.playerHp<=0?'red':'mint'}" id="nextBattle">${battle.playerHp<=0?'กลับฐาน':'ข้อต่อไป'}</button><button class="btn small dark" id="bookmarkBtn">${state.bookmarks.includes(q.id)?'★ เก็บแล้ว':'☆ เก็บทบทวน'}</button></div></div>`;$("#bookmarkBtn").onclick=()=>toggleBookmark(q.id);$("#nextBattle").onclick=()=>{if(battle.playerHp<=0){finishBattle(true);return}battle.index++;battle.selected=null;battle.locked=false;battle.hidden=[];if(battle.enemyHp<=0){battle.enemyHp=battle.enemyMax;sfx.win();state.coins+=10;save();showToast("ปราบศัตรูสำเร็จ +10 เหรียญ")};renderBattle()}}
function animateAttack(dmg){const p=$("#playerFighter"),e=$("#enemyFighter");p?.classList.add("attack");setTimeout(()=>e?.classList.add("hit"),150);damagePop(e,`-${dmg}`)}
function animateHurt(dmg){const p=$("#playerFighter");p?.classList.add("hurt");damagePop(p,dmg?`-${dmg}`:"BLOCK")}
function damagePop(el,text){if(!el)return;const a=document.createElement("div");a.className="damage-pop";a.textContent=text;a.style.left=(el.offsetLeft+40)+"px";a.style.top=(el.offsetTop+10)+"px";el.parentElement.appendChild(a);setTimeout(()=>a.remove(),1000)}
function toggleBookmark(id){state.bookmarks.includes(id)?state.bookmarks=state.bookmarks.filter(x=>x!==id):state.bookmarks.push(id);save();showToast(state.bookmarks.includes(id)?"เก็บเข้าห้องทบทวนแล้ว":"นำออกจากห้องทบทวนแล้ว");if(battle)renderBattle()}
function finishBattle(defeat=false){const result=battle,score=result?result.correct:0,total=result?result.pool.length:0;view.innerHTML=`<section class="panel pixel-box"><div class="result-hero pixel-box"><div class="eyebrow">${defeat?'MISSION RETREAT':'MISSION COMPLETE'}</div><b>${score}/${total}</b><h2>${defeat?'ถอยมาตั้งหลัก แล้วกลับไปลุยใหม่':'ภารกิจเสร็จสิ้น!'}</h2><p>${score/Math.max(total,1)>=.8?'ยอดเยี่ยม ความแม่นของคุณพร้อมลุยด่านยากขึ้น':'ทบทวนข้อที่พลาด แล้วลองอีกครั้งจะเห็นพัฒนาการชัดเจน'}</p></div><div class="hero-actions"><button class="btn" id="againBattle">ฝึกอีกชุด</button><button class="btn mint" data-go="review">ทบทวนข้อพลาด</button><button class="btn dark" data-go="home">กลับฐาน</button></div></section>`;battle=null;bindCommon();$("#againBattle").onclick=()=>go("practice")}
function renderExamLobby(){view.innerHTML=`<section class="panel pixel-box"><div class="panel-title"><div><h2>สนามสอบใหญ่</h2><small>เลือกจำนวนข้อ เวลา และขอบเขตก่อนเปิดประตูสนาม</small></div></div><div class="filter-row"><label>ขอบเขต <select id="examModule"><option value="all">ทุกดินแดน</option>${D.modules.map(m=>`<option value="${m.id}">${m.icon} ${esc(m.title)}</option>`).join("")}</select></label><label>จำนวนข้อ <select id="examCount"><option>30</option><option selected>60</option><option>100</option></select></label><label>เวลา <select id="examMinutes"><option value="30">30 นาที</option><option value="60" selected>60 นาที</option><option value="90">90 นาที</option></select></label></div><div class="mode-grid"><button class="mode-card" id="startExam"><div class="mode-icon">⏱️</div><h3>เริ่มสนามสอบ</h3><p>ซ่อนเฉลยจนกว่าจะส่งข้อสอบ เปลี่ยนคำตอบและข้ามข้อได้</p><span class="tag">EXAM MODE</span></button><button class="mode-card" id="quickExam"><div class="mode-icon">⚡</div><h3>ด่านด่วน 20 ข้อ</h3><p>จับเวลา 20 นาที เหมาะกับการซ้อมทุกวัน</p><span class="tag">SPEED RUN</span></button><button class="mode-card" id="bossExam"><div class="mode-icon">👑</div><h3>ศึกบอส 80 ข้อ</h3><p>คัดระดับกลางและยากจากทุกดินแดน</p><span class="tag">FINAL BOSS</span></button></div></section>`;$("#startExam").onclick=()=>beginExam(Number($("#examCount").value),Number($("#examMinutes").value),$("#examModule").value,false);$("#quickExam").onclick=()=>beginExam(20,20,"all",false);$("#bossExam").onclick=()=>beginExam(80,100,"all",true)}
function beginExam(count,minutes,mid,boss){let pool=D.questions.filter(q=>mid==="all"||q.module===mid);if(boss)pool=pool.filter(q=>q.difficulty!=="ง่าย");pool=shuffle(pool).slice(0,Math.min(count,pool.length));exam={pool,answers:Array(pool.length).fill(null),index:0,end:Date.now()+minutes*60000,minutes};renderExam();timer=setInterval(updateTimer,500);updateTimer()}
function renderExam(){const q=exam.pool[exam.index],m=module(q.module);view.innerHTML=`<div class="exam-layout"><section class="panel pixel-box"><div class="panel-title"><div><h2>ข้อ ${exam.index+1} จาก ${exam.pool.length}</h2><small>${m.icon} ${esc(m.title)}</small></div><div class="timer" id="timerText">--:--</div></div><div class="question-meta"><span class="chip">${esc(q.difficulty)}</span><span class="chip">${esc(q.type)}</span></div><div class="question-text">${esc(q.question)}</div><div class="options">${q.options.map((o,i)=>`<button class="option ${exam.answers[exam.index]===i?'selected':''}" data-exam-answer="${i}"><span class="letter">${letters[i]}</span>${esc(o)}</button>`).join("")}</div><div class="battle-actions"><button class="btn small dark" id="prevExam" ${exam.index===0?'disabled':''}>← ก่อนหน้า</button><div><button class="btn small" id="nextExam">${exam.index===exam.pool.length-1?'ตรวจรายการ':'ข้อต่อไป →'}</button> <button class="btn small red" id="submitExam">ส่งข้อสอบ</button></div></div></section><aside class="panel pixel-box exam-side"><div class="panel-title"><div><h2>กระดาษคำตอบ</h2><small><span id="answeredCount">${exam.answers.filter(x=>x!==null).length}</span> / ${exam.pool.length} ข้อ</small></div></div><div class="question-grid">${exam.pool.map((_,i)=>`<button data-qnav="${i}" class="${exam.answers[i]!==null?'answered':''} ${i===exam.index?'current':''}">${i+1}</button>`).join("")}</div></aside></div>`;$$('[data-exam-answer]').forEach(b=>b.onclick=()=>{exam.answers[exam.index]=Number(b.dataset.examAnswer);sfx.select();renderExam();updateTimer()});$$('[data-qnav]').forEach(b=>b.onclick=()=>{exam.index=Number(b.dataset.qnav);renderExam();updateTimer()});$("#prevExam").onclick=()=>{exam.index--;renderExam();updateTimer()};$("#nextExam").onclick=()=>{if(exam.index<exam.pool.length-1)exam.index++;else exam.index=exam.answers.findIndex(x=>x===null)>=0?exam.answers.findIndex(x=>x===null):exam.index;renderExam();updateTimer()};$("#submitExam").onclick=confirmFinish}
function updateTimer(){if(!exam)return;const left=exam.end-Date.now();if(left<=0){finishExam();return}const sec=Math.floor(left/1000),m=Math.floor(sec/60),s=sec%60;const el=$("#timerText");if(el)el.textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function confirmFinish(){const blank=exam.answers.filter(x=>x===null).length;openModal(`<h2 id="modalTitle">ส่งข้อสอบหรือไม่?</h2><p>${blank?`ยังไม่ได้ตอบ <strong>${blank}</strong> ข้อ":"ตอบครบทุกข้อแล้ว"}</p><div class="hero-actions"><button class="btn red" id="confirmSubmit">ยืนยันส่งข้อสอบ</button><button class="btn dark" id="cancelSubmit">กลับไปตรวจ</button></div>`);$("#confirmSubmit").onclick=()=>{closeModal();finishExam()};$("#cancelSubmit").onclick=closeModal}
function finishExam(){clearInterval(timer);timer=null;if(!exam)return;let score=0;const by={};exam.pool.forEach((q,i)=>{const a=exam.answers[i],ok=a===q.answer;if(a!==null)record(q,ok);if(ok)score++;const x=by[q.module]||(by[q.module]={total:0,correct:0});x.total++;if(ok)x.correct++});const pct=Math.round(score/exam.pool.length*100);state.examHistory.unshift({date:new Date().toLocaleString("th-TH"),score,total:exam.pool.length,pct});state.examHistory=state.examHistory.slice(0,20);save();const result=exam;exam=null;sfx.win();view.innerHTML=`<section class="panel pixel-box"><div class="result-hero pixel-box"><div class="eyebrow">EXAM RESULT</div><b>${pct}%</b><h2>${pct>=80?'ผ่านด่านอย่างสง่างาม':pct>=60?'ใกล้ถึงเป้าหมาย':'กลับไปเก็บเลเวลอีกนิด'}</h2><p>${score} คะแนน จาก ${result.pool.length} ข้อ</p></div><div class="section-head"><div><h2>ผลรายดินแดน</h2><p>ใช้เลือกด่านที่จะฝึกต่อ</p></div></div><div class="breakdown">${Object.entries(by).map(([id,x])=>`<div class="break-card pixel-box"><strong>${module(id).icon} ${esc(module(id).title)}</strong><b>${x.correct}/${x.total}</b><small>${Math.round(x.correct/x.total*100)}%</small></div>`).join("")}</div><div class="hero-actions"><button class="btn" data-go="exam">สอบใหม่</button><button class="btn mint" data-go="review">ทบทวนข้อผิด</button><button class="btn dark" data-go="home">กลับฐาน</button></div></section>`;bindCommon()}
function weakQuestions(){return D.questions.filter(q=>{const r=state.records[q.id];return state.bookmarks.includes(q.id)||!r||r.lastWrong||r.correct/r.attempts<.7})}
function renderReview(){const qs=weakQuestions();view.innerHTML=`<section class="panel pixel-box"><div class="panel-title"><div><h2>ห้องทบทวน</h2><small>รวมข้อที่เก็บไว้ เคยตอบผิด หรือยังไม่แม่น</small></div><button class="btn small" id="reviewBattle" ${qs.length?'':'disabled'}>ฝึกชุดนี้</button></div>${qs.length?`<div class="review-list">${qs.slice(0,60).map(q=>{const r=state.records[q.id],pct=r?Math.round(r.correct/r.attempts*100):0;return `<article class="review-card pixel-box"><div><h3>${module(q.module).icon} ${esc(q.question)}</h3><p>${esc(module(q.module).title)} • ความแม่น ${pct}% ${state.bookmarks.includes(q.id)?'• ★ เก็บไว้':''}</p></div><button class="btn small dark" data-one="${q.id}">ฝึกข้อนี้</button></article>`}).join("")}</div>`:`<div class="empty">🎉 ไม่มีข้อค้างทบทวนในตอนนี้</div>`}</section>`;$("#reviewBattle")?.addEventListener("click",()=>{battle={pool:shuffle(qs).slice(0,15),index:0,playerHp:100,enemyHp:110,enemyMax:110,combo:0,selected:null,locked:false,hidden:[],shield:false,skills:{fifty:1,heal:1,shield:1,hint:1},boss:false,correct:0};renderBattle()});$$('[data-one]').forEach(b=>b.onclick=()=>{const q=D.questions.find(x=>x.id===Number(b.dataset.one));battle={pool:[q],index:0,playerHp:100,enemyHp:40,enemyMax:40,combo:0,selected:null,locked:false,hidden:[],shield:false,skills:{fifty:1,heal:1,shield:1,hint:1},boss:false,correct:0};renderBattle()})}
function renderCodex(){view.innerHTML=`<section class="panel pixel-box"><div class="panel-title"><div><h2>คัมภีร์ความรู้</h2><small>สูตรจำสั้น ๆ สำหรับเรียกคืนก่อนเข้าสนาม</small></div></div><div class="codex-grid">${D.codex.map(c=>`<article class="codex-card pixel-box"><div class="codex-icon">${c.icon}</div><h3>${esc(c.title)}</h3><ul>${c.items.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></article>`).join("")}</div><div class="section-head"><div><h2>หอจดหมายเหตุ</h2><p>เปิดต้นทางเมื่อต้องตรวจข้อมูลกฎหมาย นโยบาย หรือบุคคลปัจจุบัน</p></div></div><div class="codex-grid">${D.sources.map(s=>`<article class="codex-card pixel-box"><h3>${esc(s.title)}</h3><p>${esc(s.note)}</p><div class="source-links"><a href="${s.url}" target="_blank" rel="noopener">เปิดแหล่งทางการ ↗</a></div></article>`).join("")}</div></section>`}
function renderProfile(){const s=stats(),ach=[{icon:"⚔️",name:"ก้าวแรก",desc:"ตอบข้อสอบครั้งแรก",ok:s.attempted>=1},{icon:"🔥",name:"คอมโบ 10",desc:"ตอบถูกต่อเนื่อง 10 ข้อ",ok:state.maxCombo>=10},{icon:"📚",name:"นักสำรวจ",desc:"ทำข้อสอบอย่างน้อย 8 ดินแดน",ok:D.modules.filter(m=>moduleStats(m.id).done>0).length>=8},{icon:"👑",name:"ผู้พิชิต",desc:"ได้คะแนนสนามสอบอย่างน้อย 80%",ok:state.examHistory.some(x=>x.pct>=80)},{icon:"💎",name:"คลังสมบัติ",desc:"สะสม 300 เหรียญ",ok:state.coins>=300},{icon:"🌟",name:"ปรมาจารย์",desc:"ขึ้นถึงเลเวล 20",ok:level()>=20}];view.innerHTML=`<section class="panel pixel-box"><div class="panel-title"><div><h2>สมุดนักผจญภัย</h2><small>เลเวล ${level()} • ${rank()}</small></div></div><div class="profile-grid"><div><div class="dashboard"><div class="stat-card pixel-box"><b>${s.accuracy}%</b><span>ความแม่นรวม</span></div><div class="stat-card pixel-box"><b>${s.attempts}</b><span>จำนวนครั้งที่ตอบ</span></div><div class="stat-card pixel-box"><b>${state.examHistory.length}</b><span>รอบสนามสอบ</span></div><div class="stat-card pixel-box"><b>${state.bookmarks.length}</b><span>ข้อที่เก็บไว้</span></div></div><div class="section-head"><div><h2>พลังรายดินแดน</h2></div></div>${D.modules.map(m=>{const x=moduleStats(m.id);return `<div class="chart-row"><span>${m.icon} ${esc(m.title)}</span><div class="bar"><i style="width:${x.accuracy}%"></i></div><b>${x.accuracy}%</b></div>`}).join("")}</div><div><div class="section-head"><div><h2>เหรียญตรา</h2></div></div><div class="achievement-grid">${ach.map(a=>`<article class="achievement pixel-box ${a.ok?'unlocked':''}"><span class="medal">${a.icon}</span><span><h3>${esc(a.name)}</h3><p>${esc(a.desc)}</p></span></article>`).join("")}</div><div class="section-head"><div><h2>ประวัติสนามสอบ</h2></div></div>${state.examHistory.length?state.examHistory.slice(0,8).map(x=>`<div class="review-card pixel-box"><div><h3>${x.pct}% • ${x.score}/${x.total}</h3><p>${esc(x.date)}</p></div></div>`).join(""):'<div class="empty">ยังไม่มีประวัติสนามสอบ</div>'}</div></div></section>`}
function settings(){openModal(`<h2 id="modalTitle">⚙ ตั้งค่าเกม</h2><div class="setting-row"><span>เพลงประกอบ</span><button class="btn small ${state.settings.music?'mint':'dark'}" id="setMusic">${state.settings.music?'เปิด':'ปิด'}</button></div><div class="setting-row"><span>เสียงเอฟเฟกต์</span><button class="btn small ${state.settings.sound?'mint':'dark'}" id="setSound">${state.settings.sound?'เปิด':'ปิด'}</button></div><div class="setting-row"><span>ระดับเสียง</span><input id="volume" type="range" min="0" max="1" step="0.05" value="${state.settings.volume}"></div><div class="setting-row"><span>ลดการเคลื่อนไหว</span><input id="reduce" type="checkbox" ${state.settings.reduced?'checked':''}></div><div class="setting-row"><span>เวอร์ชันคัมภีร์</span><b>${D.version} • ${D.questions.length} ข้อ</b></div><p><button class="btn small red" id="resetData">เริ่มความคืบหน้าใหม่</button></p>`);$("#setMusic").onclick=()=>{musicToggle();settings()};$("#setSound").onclick=()=>{soundToggle();settings()};$("#volume").oninput=e=>{state.settings.volume=Number(e.target.value);save()};$("#reduce").onchange=e=>{state.settings.reduced=e.target.checked;save()};$("#resetData").onclick=()=>{if(confirm("ล้างความคืบหน้า คะแนน และประวัติทั้งหมดหรือไม่?")){localStorage.removeItem(STORAGE);state=structuredClone(defaults);dailyReset();closeModal();go("home");showToast("เริ่มการเดินทางใหม่แล้ว")}}}
function bindCommon(){$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-module]').forEach(b=>b.onclick=()=>openZone(b.dataset.module))}
function bindGlobal(){$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{sfx.select();go(b.dataset.view)}));$("#musicBtn").onclick=musicToggle;$("#soundBtn").onclick=soundToggle;$("#settingsBtn").onclick=settings;$("#modalClose").onclick=closeModal;modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==="Escape")closeModal();if(battle&&!battle.locked&&["1","2","3","4"].includes(e.key)){battle.selected=Number(e.key)-1;renderBattle()}if(battle&&e.key==="Enter"&&battle.selected!==null&&!battle.locked)submitBattle()});document.addEventListener('pointerdown',()=>{if(state.settings.music)startMusic()},{once:true})}
function init(){dailyReset();const errors=validate();$("#avatarArt").innerHTML='<div class="pixel-head"></div>';bindGlobal();updateHud();if(errors.length){console.error(errors);view.innerHTML=`<section class="panel pixel-box"><h2>พบข้อผิดพลาดในคลังข้อสอบ</h2><pre>${esc(errors.join("\n"))}</pre></section>`;return}go("home")}
init();
})();
